# Generated by Django 5.2.6 on 2025-09-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Ваше имя')),
                ('ticket_number', models.PositiveIntegerField(default='01', max_length=2, verbose_name='Введите номер билета')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_name', models.CharField(max_length=20, verbose_name='Введите название команды')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='horse_race.member')),
            ],
            options={
                'verbose_name': 'Конь',
                'verbose_name_plural': 'Кони',
            },
        ),
    ]
