# Generated by Django 5.2.6 on 2025-09-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race_name', models.IntegerField(max_length=2, verbose_name='Введите номер тура ')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='horse_race.member')),
            ],
            options={
                'verbose_name': 'тур',
                'verbose_name_plural': 'туры',
            },
        ),
        migrations.DeleteModel(
            name='Horse',
        ),
    ]
