# Generated by Django 5.2.6 on 2025-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_race', '0002_race_delete_horse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ticket_number',
            field=models.PositiveIntegerField(default='01', verbose_name='Введите номер билета'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_name',
            field=models.IntegerField(verbose_name='Введите номер тура '),
        ),
    ]
