# Generated by Django 5.2.6 on 2025-09-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='укажите название книги')),
                ('images', models.ImageField(upload_to='books/', verbose_name='загрузите фото')),
                ('description', models.TextField(verbose_name='укажите описание книги')),
                ('link_book', models.URLField(blank=True, verbose_name='вставьте доп ссылку на контент')),
                ('category_books', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Учебное', 'Учебное'), ('Детективы', 'Детективы')], default='Фантастика', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Введите почту автора')),
                ('file', models.FileField(blank=True, upload_to='media/')),
                ('size', models.IntegerField(blank=True, verbose_name='Введите количество страниц')),
                ('tags', models.TextField(verbose_name='укажите теги книги')),
            ],
            options={
                'verbose_name': 'книгу',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Напишите отзыв')),
                ('stars', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], default='*', max_length=50, verbose_name='Поставьте оценку')),
                ('choice_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='books.books', verbose_name='Выберите книгу для написания отзыва')),
            ],
        ),
    ]
