# Generated by Django 5.2.6 on 2025-09-19 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название заказа')),
                ('choice_type', models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено')], max_length=50, verbose_name='Выберите вариант')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('card_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Неверный формат номера карты.', regex='^(?:4\\d{12}(?:\\d{3})?|5[1-5]\\d{14}|6(?:011|5\\d\\d)\\d{12}|3[47]\\d{13}|3(?:0[0-5]|[68]\\d)\\d{11}|(?:2131|1800)\\d{11})$')], verbose_name='Номер карты')),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvv_code', models.CharField(max_length=4)),
            ],
        ),
    ]
